# Generated by Django 6.0.3 on 2026-04-10 15:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField()),
                ('service_slug', models.CharField(max_length=100)),
                ('service_name', models.CharField(blank=True, max_length=100)),
                ('aspect_id', models.IntegerField()),
                ('aspect_slug', models.CharField(blank=True, max_length=100)),
                ('aspect_description', models.CharField(max_length=200)),
                ('commune_id', models.IntegerField(blank=True, null=True)),
                ('commune_name', models.CharField(blank=True, max_length=50)),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('is_rural', models.BooleanField(default=False)),
                ('hamlet_name', models.CharField(blank=True, help_text='Nombre de la vereda si is_rural=True', max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_source', models.CharField(choices=[('gps', 'GPS automático'), ('manual', 'Pin manual en mapa'), ('centroid', 'Centroide del barrio')], default='gps', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Recibida'), ('under_review', 'En revisión'), ('closed', 'Cerrada')], default='received', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Denuncia ciudadana',
                'verbose_name_plural': 'Denuncias ciudadanas',
                'db_table': 'urbaser_complaint',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_slug'], name='idx_complaint_service'), models.Index(fields=['status'], name='idx_complaint_status'), models.Index(fields=['created_at'], name='idx_complaint_date'), models.Index(fields=['commune_id'], name='idx_complaint_commune')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='infra_servicios_publicos_urbaser.complaint')),
            ],
            options={
                'verbose_name': 'Evidencia fotográfica',
                'verbose_name_plural': 'Evidencias fotográficas',
                'db_table': 'urbaser_evidence',
            },
        ),
    ]
