# Generated by Django 6.0.3 on 2026-04-10 16:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_servicios_publicos_urbaser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='ID del polígono en el cronograma PDF de Urbaser', unique=True)),
                ('name', models.CharField(max_length=300)),
                ('zone_type', models.CharField(choices=[('park', 'Parque público'), ('road_divider', 'Separador vial'), ('bike_path', 'Ciclovía'), ('roundabout', 'Glorieta / rotonda'), ('sports', 'Polideportivo'), ('other', 'Otro')], default='park', max_length=20)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Área en m² del cronograma PDF', max_digits=12, null=True)),
                ('cycle_days', models.IntegerField(default=11, help_text='Días entre cortes según contrato')),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Polígono del área — null hasta cruzar con shapefiles POT', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Zona verde',
                'verbose_name_plural': 'Zonas verdes',
                'db_table': 'urbaser_green_zone',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SweepingMacroRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('zone_type', models.CharField(choices=[('residential', 'Residencial — comunas'), ('main_roads', 'Vías principales'), ('historic_center', 'Centro histórico'), ('market', 'Plazas de mercado'), ('sunday', 'Servicio dominical')], default='residential', max_length=20)),
                ('communes_text', models.CharField(blank=True, help_text='Ej: "1,2,3,8,9"', max_length=50)),
                ('days_text', models.CharField(blank=True, help_text='Ej: "Lu-Ju", "Lu-Sá", "Domingo"', max_length=50)),
                ('schedule_text', models.CharField(blank=True, help_text='Texto original del horario: "6:00"', max_length=100)),
                ('start_time', models.TimeField(blank=True, help_text='Parseado para comparación numérica en SLA', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Null si no hay fin explícito en el PPS', null=True)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Área de cobertura — null hasta tener polígonos oficiales', null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Macroruta de barrido',
                'verbose_name_plural': 'Macrorutas de barrido',
                'db_table': 'urbaser_sweeping_macroroute',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CuttingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('executed', models.BooleanField(default=False)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='infra_servicios_publicos_urbaser.greenzone')),
            ],
            options={
                'verbose_name': 'Programación de corte',
                'verbose_name_plural': 'Programaciones de corte',
                'db_table': 'urbaser_cutting_schedule',
                'ordering': ['scheduled_date'],
                'unique_together': {('zone', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('intervention_type', models.CharField(choices=[('grass_cut', 'Corte de césped'), ('tree_pruning', 'Poda de árbol')], default='grass_cut', max_length=15)),
                ('recorded_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='infra_servicios_publicos_urbaser.cuttingschedule')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='infra_servicios_publicos_urbaser.greenzone')),
            ],
            options={
                'verbose_name': 'Intervención registrada',
                'verbose_name_plural': 'Intervenciones registradas',
                'db_table': 'urbaser_intervention',
                'ordering': ['-execution_date'],
            },
        ),
        migrations.CreateModel(
            name='SweepingMicroRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.CharField(blank=True, help_text='Del shapefile: VC1, VARIANT, VAP-2', max_length=50)),
                ('neighborhood_id', models.IntegerField(blank=True, null=True)),
                ('neighborhood_name', models.CharField(blank=True, max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('macroroute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microroutes', to='infra_servicios_publicos_urbaser.sweepingmacroroute')),
            ],
            options={
                'verbose_name': 'Microruta de barrido',
                'verbose_name_plural': 'Microrutas de barrido',
                'db_table': 'urbaser_sweeping_microroute',
                'ordering': ['macroroute__code'],
            },
        ),
    ]
