# Generated by Django 6.0.3 on 2026-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_servicios_publicos_urbaser', '0002_greenzone_sweepingmacroroute_cuttingschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommuneMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune_id', models.IntegerField()),
                ('commune_name', models.CharField(max_length=50)),
                ('service_slug', models.CharField(max_length=100)),
                ('total_complaints', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('total_violations', models.IntegerField(default=0)),
                ('violation_rate', models.FloatField(default=0.0, help_text='Fracción 0.0–1.0. violations / alerts')),
                ('period', models.DateField(help_text='Primer día del mes calculado')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica por comuna',
                'verbose_name_plural': 'Métricas por comuna',
                'db_table': 'urbaser_commune_metric',
                'ordering': ['-period', 'commune_id'],
                'indexes': [models.Index(fields=['period', 'service_slug'], name='idx_metric_period')],
                'unique_together': {('commune_id', 'service_slug', 'period')},
            },
        ),
        migrations.CreateModel(
            name='SLAAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.IntegerField(db_index=True)),
                ('service_slug', models.CharField(max_length=100)),
                ('route_type', models.CharField(choices=[('sweeping_microroute', 'Microruta de barrido'), ('green_zone', 'Zona verde')], max_length=25)),
                ('route_id', models.IntegerField()),
                ('macroroute_code', models.CharField(blank=True, help_text='Código del PPS para reportes oficiales: B211, 611…', max_length=10)),
                ('violation', models.BooleanField()),
                ('distance_meters', models.FloatField(blank=True, help_text='Distancia en metros entre la denuncia y la ruta', null=True)),
                ('days_since_intervention', models.IntegerField(blank=True, help_text='Solo zonas verdes — días desde el último corte', null=True)),
                ('confidence', models.CharField(choices=[('high', 'Alta — coordenada GPS'), ('medium', 'Media — pin manual'), ('low', 'Baja — centroide barrio')], default='high', max_length=6)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta SLA',
                'verbose_name_plural': 'Alertas SLA',
                'db_table': 'urbaser_sla_alert',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['complaint_id'], name='idx_alert_complaint'), models.Index(fields=['violation'], name='idx_alert_violation'), models.Index(fields=['service_slug'], name='idx_alert_service'), models.Index(fields=['generated_at'], name='idx_alert_date'), models.Index(fields=['route_type', 'route_id'], name='idx_alert_route')],
            },
        ),
    ]
