# Generated by Django 6.0.3 on 2026-04-10 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_neighborhood_geom_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Nombre del ícono Lucide. Ej: alert-circle, camera', max_length=50)),
                ('what_is', models.TextField(help_text='Explicación de qué es este problema y cuándo ocurre')),
                ('how_to_evidence', models.TextField(help_text='Cómo el ciudadano puede documentar este problema con fotos')),
                ('response_time', models.CharField(blank=True, help_text='Tiempo de respuesta según contrato. Ej: 24 horas', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.aspect')),
            ],
            options={
                'verbose_name': 'Contenido informativo del aspecto',
                'verbose_name_plural': 'Contenidos informativos de aspectos',
                'db_table': 'core_aspect_content',
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Nombre del ícono Lucide. Ej: trash-2, leaf, droplets', max_length=50)),
                ('summary', models.CharField(help_text='Descripción corta visible en el formulario (máx 300 chars)', max_length=300)),
                ('full_description', models.TextField(help_text='Descripción completa del servicio y sus obligaciones contractuales')),
                ('frequency', models.CharField(blank=True, help_text='Ej: Lunes a sábado según macroruta de tu zona', max_length=200)),
                ('citizen_rights', models.TextField(blank=True, help_text='Derechos del ciudadano según el PPS 2024')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.service')),
            ],
            options={
                'verbose_name': 'Contenido informativo del servicio',
                'verbose_name_plural': 'Contenidos informativos de servicios',
                'db_table': 'core_service_content',
            },
        ),
    ]
